### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by NimishKashyap** [technocrats-robotics/tcr-website#154]
## Task List (High Priority): 

- [ ] Fix "Contact Us" Form and make it functional.
- [ ] Create form for Recruitment and integrate in the website.
- [ ] Improve Typography and spacing.
- [ ] Improve responsiveness.
- [ ] Fix TCR-utility microservice.
